name: Release

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - run: echo "Triggered by ${GITHUB_REF}."

      - name: Get version
        id: versioning
        uses: sceccotti89/Github-Action-Versioning@v1.0.5
      - name: Get the output version
        run: echo "Version = ${{ steps.versioning.outputs.version }}"